export const Constants = {
    "Personal_permanent_report_column_l1Admin":[
        { key: "unit", value: "grid_columns.reports.unit", sortRequired: false },
        { key: "firstName", value: "grid_columns.reports.firstName", sortRequired: false },
        { key: "lastName", value: "grid_columns.reports.lastName", sortRequired: false },
        { key: "cellNumber", value: "grid_columns.reports.cellNumber", sortRequired: false },
        { key: "checkInDate", value: "grid_columns.reports.checkin_date", sortRequired: false },
        { key: "checkInTime", value: "grid_columns.reports.checkin_time", sortRequired: false },
        { key: "checkOutDate", value: "grid_columns.reports.checkout_date", sortRequired: false },
        { key: "checkOutTime", value: "grid_columns.reports.checkout_time", sortRequired: false },
    ],
    "Personal_permanent_report_column":[
        // { key: "cardNo", value: "grid_columns.reports.cardNo", sortRequired: false },
        { key: "firstName", value: "grid_columns.reports.firstName", sortRequired: false },
        { key: "lastName", value: "grid_columns.reports.lastName", sortRequired: false },
        { key: "cellNumber", value: "grid_columns.reports.cellNumber", sortRequired: false },
        { key: "checkInDate", value: "grid_columns.reports.checkin_date", sortRequired: false },
        { key: "checkInTime", value: "grid_columns.reports.checkin_time", sortRequired: false },
        { key: "checkOutDate", value: "grid_columns.reports.checkout_date", sortRequired: false },
        { key: "checkOutTime", value: "grid_columns.reports.checkout_time", sortRequired: false },
    ],
    "Vehicle_permanent_report_column":[
        { key: "firstName", value: "grid_columns.reports.firstName", sortRequired: false },
        { key: "lastName", value: "grid_columns.reports.lastName", sortRequired: false },
        { key: "vehicleNo", value: "grid_columns.reports.vehicalNo", sortRequired: false },
        { key: "vehicleType", value: "grid_columns.reports.vehicleType", sortRequired: false },
        { key: "cellNumber", value: "grid_columns.reports.cellNumber", sortRequired: false },
        { key: "checkInDate", value: "grid_columns.reports.checkin_date", sortRequired: false },
        { key: "checkInTime", value: "grid_columns.reports.checkin_time", sortRequired: false },
        { key: "checkOutDate", value: "grid_columns.reports.checkout_date", sortRequired: false },
        { key: "checkOutTime", value: "grid_columns.reports.checkout_time", sortRequired: false },
    ],
    "Vehicle_permanent_report_column_l1Admin":[
        { key: "unit", value: "grid_columns.reports.unit", sortRequired: false },
        { key: "firstName", value: "grid_columns.reports.firstName", sortRequired: false },
        { key: "lastName", value: "grid_columns.reports.lastName", sortRequired: false },
        { key: "vehicleNo", value: "grid_columns.reports.vehicalNo", sortRequired: false },
        { key: "vehicleType", value: "grid_columns.reports.vehicleType", sortRequired: false },
        { key: "cellNumber", value: "grid_columns.reports.cellNumber", sortRequired: false },
        { key: "checkInDate", value: "grid_columns.reports.checkin_date", sortRequired: false },
        { key: "checkInTime", value: "grid_columns.reports.checkin_time", sortRequired: false },
        { key: "checkOutDate", value: "grid_columns.reports.checkout_date", sortRequired: false },
        { key: "checkOutTime", value: "grid_columns.reports.checkout_time", sortRequired: false },
    ],
    "daily_pass_report_column":[
        { key: "unit", value: "grid_columns.reports.unit", sortRequired: false },
        { key: "firstName", value: "grid_columns.reports.firstName", sortRequired: false },
        { key: "lastName", value: "grid_columns.reports.lastName", sortRequired: false },
        { key: "cellNumber", value: "grid_columns.reports.cellNumber", sortRequired: false },
        { key: "emailAddress", value: "grid_columns.reports.email_Address", sortRequired: false },
        { key: "contractorName", value: "grid_columns.reports.contractorName", sortRequired: false },
        { key: "gender", value: "grid_columns.reports.gender", sortRequired: false },
        { key: "purpose", value: "grid_columns.reports.purpose", sortRequired: false },
        { key: "nameOfPersonToMeet", value: "grid_columns.reports.nameOfPersonToMeet", sortRequired: false },
        { key: "startDate", value: "grid_columns.reports.start_date", sortRequired: false },
        { key: "startTime", value: "grid_columns.reports.start_time", sortRequired: false },
        { key: "vehicleNo", value: "grid_columns.reports.vehicleNo", sortRequired: false },
        { key: "checkInDate", value: "grid_columns.reports.checkin_date", sortRequired: false },
        { key: "checkInTime", value: "grid_columns.reports.checkin_time", sortRequired: false },
        { key: "checkOutDate", value: "grid_columns.reports.checkout_date", sortRequired: false },
        { key: "checkOutTime", value: "grid_columns.reports.checkout_time", sortRequired: false }
    ],
    "daily_pass_report_column_tenant":[
        { key: "firstName", value: "grid_columns.reports.firstName", sortRequired: false },
        { key: "lastName", value: "grid_columns.reports.lastName", sortRequired: false },
        { key: "cellNumber", value: "grid_columns.reports.cellNumber", sortRequired: false },
        { key: "emailAddress", value: "grid_columns.reports.email_Address", sortRequired: false },
        { key: "contractorName", value: "grid_columns.reports.contractorName", sortRequired: false },
        { key: "gender", value: "grid_columns.reports.gender", sortRequired: false },
        { key: "purpose", value: "grid_columns.reports.purpose", sortRequired: false },
        { key: "nameOfPersonToMeet", value: "grid_columns.reports.nameOfPersonToMeet", sortRequired: false },
        { key: "startDate", value: "grid_columns.reports.start_date", sortRequired: false },
        { key: "startTime", value: "grid_columns.reports.start_time", sortRequired: false },
        { key: "vehicleNo", value: "grid_columns.reports.vehicleNo", sortRequired: false },
        { key: "checkInDate", value: "grid_columns.reports.checkin_date", sortRequired: false },
        { key: "checkInTime", value: "grid_columns.reports.checkin_time", sortRequired: false },
        { key: "checkOutDate", value: "grid_columns.reports.checkout_date", sortRequired: false },
        { key: "checkOutTime", value: "grid_columns.reports.checkout_time", sortRequired: false }
    ],
    
    "visitor_report_column": [
        { key: "visitorName", value: "grid_columns.reports.visitor_name", sortRequired: false },
        { key: "visitorPhone", value: "grid_columns.reports.visitor_cell_no", sortRequired: false },
        { key: "visitorCompany", value: "grid_columns.reports.visitor_comapny", sortRequired: false },
        { key: "hostName", value: "grid_columns.reports.host_name", sortRequired: false },
        { key: "hostPhone", value: "grid_columns.reports.host_cell_number", sortRequired: false },
        { key: "hostEmail", value: "grid_columns.reports.host_email", sortRequired: false },
        { key: "building", value: "grid_columns.reports.building", sortRequired: false },
        { key: "checkInDate", value: "grid_columns.reports.checkin_date", sortRequired: false },
        { key: "checkInTime", value: "grid_columns.reports.checkin_time", sortRequired: false },
        { key: "checkOutDate", value: "grid_columns.reports.checkout_date", sortRequired: false },
        { key: "checkOutTime", value: "grid_columns.reports.checkout_time", sortRequired: false },
        { key: "endTime", value: "grid_columns.reports.meeting_end_time", sortRequired: false },
        { key: "visitorType", value: "grid_columns.reports.type_of_visitor", sortRequired: false },
        { key: "visitorPurposeType", value: "grid_columns.reports.purpose_of_visit", sortRequired: false },
    ],
    // appointment_report_column: [
    //     { key: "visitorName", value: "grid_columns.reports.visitor_name", sortRequired: false },
        
    //     { key: "visitorPhone", value: "grid_columns.reports.visitor_cell_no", sortRequired: false },
    //     { key: "visitorEmailId", value: "grid_columns.reports.visitor_email", sortRequired: false },

    //     { key: "visitorCompany", value: "grid_columns.reports.visitor_comapny", sortRequired: false },
    //     { key: "hostName", value: "grid_columns.reports.host_name", sortRequired: false },
    //     { key: "hostPhone", value: "grid_columns.reports.host_cell_number", sortRequired: false },
    //     { key: "hostEmail", value: "grid_columns.reports.host_email", sortRequired: false },
    //     { key: "hostCompany", value: "grid_columns.reports.host_company", sortRequired: false },
    //     { key: "building", value: "grid_columns.reports.building", sortRequired: false },

    //     // Columns for enterprise appointments table 
    //     { key: "location", value: "grid_columns.reports.appointment_location", sortRequired: false },
    //     { key: "visitorType", value: "grid_columns.reports.type_of_visitor", sortRequired: false },
    //     { key: "visitorPurposeType", value: "grid_columns.reports.purpose_of_visit", sortRequired: false },

    //     { key: "appointmentStartDate", value: "grid_columns.reports.appointment_start_date", sortRequired: false },
    //     { key: "appointmentStartTime", value: "grid_columns.reports.appointment_start_time", sortRequired: false },
    //     { key: "appointmentEndDate", value: "grid_columns.reports.appointment_end_date", sortRequired: false },
    //     { key: "appointmentEndTime", value: "grid_columns.reports.appointment_end_time", sortRequired: false },

    //     { key: "appointmentType", value: "grid_columns.reports.appointment_type", sortRequired: false },
    //     { key: "status", value: "grid_columns.reports.appointment_status", sortRequired: false },
    //     { key: "multidayAppointment", value: "grid_columns.reports.multiday_appointment", sortRequired: false },
        
       
    //     // { key: "timeInTime", value: "Time In Time", sortRequired: false },
    //     // { key: "timeOutTime", value: "Timeout Time", sortRequired: false },

    //     //Hide above two column as per discussion with nilesh and snenal
    // ],
    // hsq_report_column : [
    //     { key: "visitorName", value: "grid_columns.reports.visitor_name", sortRequired: false },
        
    //     { key: "visitorPhone", value: "grid_columns.reports.visitor_cell_no", sortRequired: false },
    //     { key: "visitorEmailId", value: "grid_columns.reports.visitor_email", sortRequired: false },

    //     { key: "visitorCompany", value: "grid_columns.reports.visitor_comapny", sortRequired: false },
    //     { key: "hostName", value: "grid_columns.reports.host_name", sortRequired: false },
    //     { key: "hostPhone", value: "grid_columns.reports.host_cell_number", sortRequired: false },
    //     { key: "hostEmail", value: "grid_columns.reports.host_email", sortRequired: false },
    //     { key: "hostCompany", value: "grid_columns.reports.host_company", sortRequired: false },
    //     { key: "building", value: "grid_columns.reports.building", sortRequired: false },
    //     { key: "appointmentStartDate", value: "grid_columns.reports.appointment_start_date", sortRequired: false },
    //     { key: "appointmentStartTime", value: "grid_columns.reports.appointment_start_time", sortRequired: false },
    //     { key: "appointmentEndDate", value: "grid_columns.reports.appointment_end_date", sortRequired: false },
    //     { key: "appointmentEndTime", value: "grid_columns.reports.appointment_end_time", sortRequired: false },

    //     { key: "appointmentType", value: "grid_columns.reports.appointment_type", sortRequired: false },
    //     { key: "status", value: "grid_columns.reports.appointment_status", sortRequired: false },
    //     { key: "multidayAppointment", value: "grid_columns.reports.multiday_appointment", sortRequired: false },
    //     { key: "hsqStatus", value: "grid_columns.reports.hsqStatus", sortRequired: false },
    //     // { key: "timeInTime", value: "Time In Time", sortRequired: false },
    //     // { key: "timeOutTime", value: "Timeout Time", sortRequired: false },

    //     //Hide above two column as per discussion with nilesh and snenal
    // ],
    // email_report_column : [
    //     { key: "employeeName", value: "EmaileportDetails.employeeName", sortRequired: false },
    //     { key: "companyName", value: "EmaileportDetails.companyName", sortRequired: false },
    //     { key: "buildingName", value: "EmaileportDetails.buildingName", sortRequired: false },
    //     { key: "username", value: "EmaileportDetails.username", sortRequired: false },
    //     { key: "emailOfRecipient", value: "EmaileportDetails.emailOfRecipient", sortRequired: false },
    //     { key: "emailSentDate", value: "EmaileportDetails.emailSentDate", sortRequired: false },
    //     { key: "emailSentTime", value: "EmaileportDetails.emailSentTime", sortRequired: false },
    //     { key: "status", value: "EmaileportDetails.status", sortRequired: false }
    // ],
    // first_time_password_change : [
    //     { key: "employeeFirstName", value: "grid_columns.reports.employee_name", sortRequired: false },
    //     { key: "userName", value: "grid_columns.reports.user_name", sortRequired: false },
    //     { key: "passwordChangeDate", value: "grid_columns.reports.password_change", sortRequired: false },
    //     { key: "passwordChangeTime", value: "grid_columns.reports.password_change_time", sortRequired: false },
    //     { key: "buildingName", value: "grid_columns.reports.building_name", sortRequired: false },
    //     { key: "companyName", value: "grid_columns.reports.company_name", sortRequired: false },
    //     { key: "cellNumber", value: "grid_columns.reports.cell_number", sortRequired: false },
    //     { key: "emailId", value: "grid_columns.reports.email_id", sortRequired: false },
    // ]
}   