export const permissionKeys = {
    SCHEDULE: "schedule",
    VISITORDETAILVIEW: "visitordetailview",
    VISITORCONTACTACTION: "visitorcontactaction",
    HOSTCONTACTACTION: "hostcontactaction",
    ACCESSALLAPPOINTMENTS: "accessAllAppointments",
    WALKINAPPROVALRIGHTS: "walkInApprovalrights",
    ARCHIVEDAPPOINTMENTS: "archivedAppointments",
    UPDATEPROFILE: "updateProfile",
    MASTERVIEWEDIT: "masterViewEdit",
    CONFIGURATION: "configuration",
    SETTING: "setting",
    REPORTS: "reports",
    DASHBOARD: "dashboard",
    RESTRICTEDVISITOR: "restrictedVisitor",
    RESTRICTVISITORADD: "restrictVisitorAdd",
    CREATEWALKIN: "createWalkIn",
    CHECKIN: "checkIn",
    CHECKOUT: "checkOut",
    PRINTBADGE: "printBadge",
    SWITCHTOKIOSMODE: "switchToKioskMode",
    SOS: "sos",
    TIMEINOUT: "timeInOut",
    WALKINAPPROVALONBEHALF: "walkinApprovalOnbehalf",
    MASTERVIEWONLY: "masterViewOnly",
    CONTRACTORENTRY: "contractorEntry",
    SUPERADMIN: "superAdmin",
    APPOINTMENT: "appointment",
    CONTRACTORPASS:"contractorEntry",
    PERMANENTPASS:"permanentPass",
    DAILYPASS:"dailyPass",
    CREATEPASS:"createpass",
    PERMANENTPASSREQUEST:"permanentPassRequest",
    PERMANENTPASSPRINT:"permanentPassPrint",
    PASSCHECKIN:"PassCheckIn",
    LEDGEREPORT:"LedgerReport"

}
export const permissionKeysWithRoute = [
    {SCHEDULE: "schedule"},
   { VISITORDETAILVIEW: "visitordetailview"},
   { VISITORCONTACTACTION: "visitorcontactaction"},
   { HOSTCONTACTACTION: "hostcontactaction"},
   { ACCESSALLAPPOINTMENTS: "accessAllAppointments"},
   { WALKINAPPROVALRIGHTS: "walkInApprovalrights"},
   { ARCHIVEDAPPOINTMENTS: "archivedAppointments"},
   { UPDATEPROFILE: "updateProfile"},
   { MASTERVIEWEDIT: "masterViewEdit",ROUTE:"master"},
   { CONFIGURATION: "configuration",ROUTE:"configure"},
    {SETTING: "setting",ROUTE:"setting"},
    { REPORTS: "reports", ROUTE: "reports" },
     { REPORTS: "reports", ROUTE: "seepzReport" },
   { DASHBOARD: "dashboard",ROUTE:"dashboard"},
    {RESTRICTEDVISITOR: "restrictedVisitor"},
    {RESTRICTVISITORADD: "restrictVisitorAdd"},
    {CREATEWALKIN: "createWalkIn"},
//    { CHECKIN: "checkIn",ROUTE:"checkIn"},
//    { CHECKOUT: "checkOut",ROUTE:"checkOut"},
   { PRINTBADGE: "printBadge"},
   { SWITCHTOKIOSMODE: "switchToKioskMode"},
   { SOS: "sos"},
    {TIMEINOUT: "timeInOut"},
   { WALKINAPPROVALONBEHALF: "walkinApprovalOnbehalf"},
    {MASTERVIEWONLY: "masterViewOnly",ROUTE:"MASTER"},
   { CONTRACTORENTRY: "contractorEntry"},
   { SUPERADMIN: "superAdmin"},
    {APPOINTMENT: "appointment",ROUTE:"appointments"},
   { CONTRACTORPASS:"contractorEntry",ROUTE:"contractor-pass"},
   { PERMANENTPASS:"permanentPass",ROUTE:"permanentPass"},
   { DAILYPASS:"dailyPass",ROUTE:"dailyPass"},
   { CREATEPASS:"createpass"},
   { PERMANENTPASSREQUEST:"permanentPassRequest",ROUTE:"permanentPassRequest"},
   { PERMANENTPASSPRINT:"permanentPassPrint",ROUTE:"permanentPassPrint"},
   { PASSCHECKIN:"PassCheckIn",ROUTE:"checkIn"},
   { PASSCHECKIN:"PassCheckIn",ROUTE:"checkOut"},
   { LEDGEREPORT:"LedgerReport",ROUTE:"seepzGeneralLedger"}

]
