export const Constants = {
  building_column: [
    { value: "Name", key: "name" },
    { value: "Status", key: "status" },
    { value: "Action", key: "action" },
  ],
  company_column: [
    { key: "name", value: "Name" },
    { key: "short_name", value: "Company Short Name" },
    { key: "building", value: "Building" },
    { key: "floor", value: "Floor" },
    { key: "cell", value: "Phone No" },
    { key: "email", value: "Email" },
    { key: "status", value: "Status" },
    { key: "department", value: "Departments" },
    { key: "employee", value: "Employees" },
    { key: "contractor", value: "Contractors" },
  ],
  department_column: [
    { value: "Name", key: "name" },
    { value: "Status", key: "status" },
    { value: "Action", key: "action" },
  ],
  employee_column: [
    { key: "name", value: "Name" },
    { key: "cell", value: "Cell number" },
    { key: "emailId", value: "Email" },
    { key: "department", value: "Department" },
    { key: "role", value: "Role" },
    { key: "status", value: "Status" },
    { key: "action", value: "Action" },
    { key: "notificationType", value: "Notification Type" },
  ],
  contractor_column: [
    { key: "name", value: "Contractor Name" },
    { key: "company", value: "Company" },
    { key: "cell", value: "Cell number" },
    { key: "emailId", value: "Email" },
    { key: "from", value: "Valid From" },
    { key: "to", value: "Valid Upto" },
    { key: "pass", value: "Print pass" },
    { key: "status", value: "Status" },
    { key: "action", value: "Action" },
  ],
  contractor_company_column: [
    { key: "company_name", value: "Name" },
    { key: "contact_person", value: "Contact Person" },
    { key: "email", value: "Email" },
    { key: "cell1", value: "Cell number 1" },
    { key: "cell2", value: "Cell number 2" },
    { key: "address", value: "Address" },
    { key: "url", value: "url" },
    { key: "status", value: "Status" },
    { key: "action", value: "Action" },
  ],
  appointment_column: [
    { key: "visitorFirstName", value: "grid_columns.appointment_column.visitor_name", sortRequired: true },
    { key: "type", value: "grid_columns.appointment_column.appointment_type", sortRequired: true },
    { key: "status", value: "grid_columns.appointment_column.status", sortRequired: true  },
    { key: "hostFirstName", value: "grid_columns.appointment_column.host_name", sortRequired: true  },
    { key: "hostCompany", value: "grid_columns.appointment_column.host_company", sortRequired: true },
    { key: "date", value: "grid_columns.appointment_column.date", sortRequired: true },
    { key: "startTime", value: "grid_columns.appointment_column.start_time", sortRequired: true },
    { key: "endTime", value: "grid_columns.appointment_column.end_time", sortRequired: true },
    { key: "action", value: "", sortRequired: false },
  ],
  visitors_details: [
    { key: "date", value: "Date" },
    { key: "hostName", value: "Host Name" },
    { key: "hostCompany", value: "Host Company" },
    { key: "hostDept", value: "Host Department" },
    { key: "checkIn", value: "Check-In" },
    { key: "checkOut", value: "Check-Out" },
  ],
};
