export enum defaultVal {
    isAuth = "true",
    isByPass = "true",
    isPrintPass= "true",
    isWalkin= "true",
    isSoftPass= "false",
    isHostRequired= "true",
    isCamera= "true",
    isLivePhoto= "true",
    isVisitorHSQ= "true",
    timeZone= "",
    dateFormat= "",
    languageCode= "",
    timeformat= 12,
    isMultiDay= "true",
    maxMultiDays= 4,
    level1Id = 0,
    level2Id= 0,
    allowWalkinApproval= "true",
    showRegisterVisitorPhotoOnVisitorPass= "true",
    showLivePhotoOnVisitorPass= "true",
    earlyCheckinMins= 30,
    lateCheckinMins= 30,
    autoCheckout= "true",
    autoCheckoutTime= "11:45",
    noCheckOutVisitorAlert= "true",
    noCheckOutVisitorAlertTime= "08:00",
    noCheckoutVisitorAlertEmail= "",
    sendNDA= "false",
    hsqAlertSendBeforeHours= 4,
    visitorCheckinAtComplex= "true",
    visitorCheckinAtBuilding= "false",
    printRegisterPhotoIfNotLivePhoto = "true",
    authenticationMethod="Both"
  }
  